/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  "/": {
    get: operations["getHello"];
  };
  "/auth/login": {
    post: operations["login"];
  };
  "/auth/register": {
    post: operations["register"];
  };
  "/auth/me": {
    get: operations["getMe"];
  };
  "/restaurants": {
    get: operations["getAll"];
  };
  "/restaurants/{id}": {
    get: operations["getOne"];
  };
  "/restaurants/search/{searchInput}": {
    get: operations["search"];
  };
};

export type components = {
  schemas: {
    LoginDto: {
      email: string;
      password: string;
    };
    AuthToken: {
      accessToken: string;
    };
    RegisterDto: {
      email: string;
      password: string;
    };
    UserResponse: {
      id: string;
      /** Format: date-time */
      createdAt: string;
      email: string;
    };
    RestaurantResponse: {
      id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      name: string;
      phone: string;
      imageSrc: string;
      address: string;
    };
    MenuItemResponse: {
      imageSrc: string;
      id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      name: string;
      description: string;
      price: number;
      restaurantId: string;
    };
    RestaurantWithMenuResponse: {
      menu: components["schemas"]["MenuItemResponse"][];
      id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      name: string;
      phone: string;
      imageSrc: string;
      address: string;
    };
    SearchResponse: {
      restaurants: components["schemas"]["RestaurantResponse"][];
      itens: components["schemas"]["MenuItemResponse"][];
    };
  };
};

export type operations = {
  getHello: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  login: {
    parameters: {};
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["AuthToken"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
  };
  register: {
    parameters: {};
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["AuthToken"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDto"];
      };
    };
  };
  getMe: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  getAll: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestaurantResponse"][];
        };
      };
    };
  };
  getOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestaurantWithMenuResponse"];
        };
      };
    };
  };
  search: {
    parameters: {
      path: {
        searchInput: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
    };
  };
};

export type external = {};
